version: '3.8'

services:
  ip-fetcher:
    # Use the published image from GitHub Container Registry
    image: ghcr.io/elitery-service-delivery/dummy-web-app:latest
    
    # For local development, uncomment the build section below:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.dev
    
    container_name: ip-fetcher-app
    
    ports:
      - "3000:3000"
    
    environment:
      - RUST_LOG=info
    
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.2'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Labels for better organization
    labels:
      - "app=ip-fetcher"
      - "environment=development"